jobs:
- job: CI-Build
  trigger: [master, releases/*]
- job: RunTests
  steps:
  - inputs: {architecture: x64, versionSpec: '3.6'}
    task: UsePythonVersion@0
  - inputs: {secureFile: panoptesConfig}
    task: DownloadSecureFile@1
  - {displayName: Install Requirements, script: pip install -r requirements.txt}
  - {displayName: Check Current Dir, script: 'echo $BUILD_REPOSITORY_LOCALPATH

      ls

      '}
  - {displayName: Test with pytest, script: 'pytest panoptes -m smoke --ENV=prod --log-file
      panoptes/logs/hello.log

      '}
