# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker
# multiple jobs get run in paralell/out of order

jobs:
- job: 'RunTests'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: echo "##vso[task.setvariable variable=sauce]crushed tomatoes"
  - script: echo "##vso[task.setvariable variable=secret.Sauce;issecret=true]crushed tomatoes with garlic"
  - script: echo "No problem reading $1 or $SAUCE" && echo "But I cannot read $SECRET_SAUCE" && echo "But I can read $2 (but the log is redacted so I do not spoil the secret)" 
  - script: pip install -r panoptes/requirements.txt
    displayName: 'pip install requirements'
  - script: mkdir logs
  - script: echo  $BUILD_REPOSITORY_LOCALPATH
  - script: PANPATH = $BUILD_REPOSITORY_LOCALPATH/panoptes
  - script: echo $PANPATH
  - script: cd $PANPATH
  - script: pytest runScript.py
    displayName: 'Running Smoke Tests'

