# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

jobs:
- job: 'Test'
  steps:
  - script: pip install --upgrade pip
  - script: pip install -r panoptes/requirements.txt
  - script: pytest panoptes/runScript.py
    displayName: 'Running Smoke Tests'

