jobs:
  - job: 'DownloadSecureFile'
    steps:
      - task: DownloadSecureFile@1
        name: GetConfigFile
        inputs:
          secureFile:  'panoptesConfig.ini'
      - script: ls $(GetConfigFile.secureFilePath)
        name: ViewFile 
      - task: CopyFiles@2
        inputs:
          sourceFolder: $(GetConfigFile.secureFilePath) # Optional
          contents: '**.ini' 
          targetFolder: $(Agent.WorkFolder)
          #cleanTargetFolder: false # Optional
          overWrite: true # Optional
          #flattenFolders: false # Optional
      - script: ls $(Agent.WorkFolder)
        name: ViewFile2             
            
  - job: 'RunTestsPROD'
    dependsOn: DownloadSecureFile
    continueOnError: True
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    - script: pip install -r requirements.txt
      displayName: 'Install Requirements'
    - script: |
        pytest panoptes -m smoke --ENV=prod --CONFIG= $(Agent.WorkFolder)/_temp/panoptesConfig.ini --junitxml=$SYSTEM_ARTIFACTSDIRECTORY/TEST-prod-smoke.xml
      displayName: 'Test with pytest'

  - job: 'RunTestsQA'
    dependsOn: DownloadSecureFile
    continueOnError: True
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    - script: pip install -r requirements.txt
      displayName: 'Install Requirements'
    - script: pytest panoptes -m smoke --ENV=qa --CONFIG= $(Agent.WorkFolder)/_temp/panoptesConfig.ini  --junitxml= $SYSTEM_ARTIFACTSDIRECTORY/TEST-qa-smoke.xml
      displayName: 'Test with pytest'
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current' # Options: current, specific
        #project: # Required when buildType == Specific
        #pipeline: # Required when buildType == Specific
        #specificBuildWithTriggering: false # Optional
        #buildVersionToDownload: 'latest' # Required when buildType == Specific# Options: latest, latestFromBranch, specific
        #branchName: 'refs/heads/master' # Required when buildType == Specific && BuildVersionToDownload == LatestFromBranch
        #buildId: # Required when buildType == Specific && BuildVersionToDownload == Specific
        #tags: # Optional
        #downloadType: 'single' # Options: single, specific
        #artifactName: # Required when downloadType == Single
        itemPattern: '**' # Optional
        downloadPath: '$(System.ArtifactsDirectory)' 
        #parallelizationLimit: '8' # Optional
  - job: UploadResults
    dependsOn: 
      - RunTestsQA
      - RunTestsPROD
    steps:
    - script: echo hello from the publish tests job  
        # PUBLISH JUNIT RESULTS
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
        testResultsFiles: '**/TEST-*.xml' 
        searchFolder: '$SYSTEM_ARTIFACTSDIRECTORY' # Optional
        mergeTestResults: false # Optional
        testRunTitle: 'API_CHECK QA'
        #buildPlatform: # Optional
        #buildConfiguration: # Optional
        publishRunAttachments: true # Optional




