jobs:
  - job: 'CI-Build'
    trigger:
      branches:
        include:
          - master
          - releases/*

  - job: 'RunTests'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    - task: DownloadSecureFile@1
      inputs:
        secureFile:  'panoptesConfig'
  #  - script: . setup.sh
    - script: pip install -r requirements.txt
      displayName: 'Install Requirements'
    - script: |
        echo $BUILD_REPOSITORY_LOCALPATH
        ls
      displayName: 'Check Current Dir'
    - script: |
        pytest panoptes -m smoke --ENV=prod --log-file panoptes/logs/hello.log
      displayName: 'Test with pytest'

