jobs:
  - job: 'RunTests'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    - task: DownloadSecureFile@1
      inputs:
        secureFile:  'panoptesConfig'
  #  - script: . setup.sh
    - script: pip install -r requirements.txt
      displayName: 'Install Requirements'
    - script: |
        echo $DOWNLOADSECUREFILE_SECUREFILEPATH
        cp $DOWNLOADSECUREFILE_SECUREFILEPATH $BUILD_REPOSITORY_LOCALPATH/panoptesConfig.ini
        echo '-----------'
        echo $BUILD_REPOSITORY_LOCALPATH
        if [ ! -f panoptesConfig.ini ]; then
          echo "File not found!"

        ls
      displayName: 'Check Current Dir'
    - script: |
        pytest panoptes -m smoke --ENV=prod --CONFIG= panoptesConfig.ini --log-file panoptes/logs/hello.log
      displayName: 'Test with pytest'

